// https://dotnetfiddle.net/pRi6zM/

// PROBLEM //

/*
Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms
will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do
not exceed four million, find the sum of the even-valued terms.
*/

// ANSWER

using System;
using System.Collections.Generic;
using System.Linq;
					
public class Program
{
	public static void Main()
	{
		Console.WriteLine(FibonacciSequence(4000000).Where(n => n % 2 == 0).Sum());
	}
	
	private static IEnumerable<int> FibonacciSequence(int ceiling)
	{
		if (ceiling < 2)
			yield break;
		
		var penultimate = 1;
		yield return penultimate;
		var ultimate = 1;
		yield return ultimate;
		
		var tempUltimate = penultimate + ultimate;
		while (tempUltimate < ceiling)
		{
			yield return tempUltimate;
			
			penultimate = ultimate;
			ultimate = tempUltimate;
			tempUltimate = penultimate + ultimate;
		}
	}
}

// 4613732